version: "3.9"

services:
  backend:
    image: localhost:9000/repository/pis/backend
    ports:
      - "8083:8083"
    container_name: backendDockerized

  frontend:
    image: localhost:9000/repository/pis/frontend
    ports:
            - "8082:3000"
    container_name: frontendDockerized

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
 
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"   
    container_name: rabbitmq
